### ISSUE TITLE
Automatical scans of folders already in the library

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#26]
Hi! 

Similarly as #23 and it's suggestion to auto remove missing files from a library, I was wondering if it would be possible for COMPASS to auto scan the folders in it's library for new additions. 
There could be a setting in the preferences on how many times these scan happen, or maybe even a button somewhere to manually start a scan, without the need to actually drag & drop the whole folder back in. 

Thanks for considering!

**Comment by DSPaul** [comment]
This a great idea! The more automation the better.

**Comment by DSPaul** [comment]
Added in v1.3.0
