### ISSUE TITLE
Right clicking tag (groups) to add (sub)tags

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#27]
Hi! 

Sorry for making many suggestions. :) 

Maybe it would be easy to be able to rightclick already made tag (groups), like you can do now to edit them, to make (sub)tags that have the same colour as the parent. 
ie with the following example, I could rightclick `Mechanics` to add a new tag `2D20` that will be blue and directly made under the `Mechanics` group; or I could rightclick `Horror` to add a new tag `Cthulhu Mythos` that will be red and directly made under the `Horror` tag. 
![afbeelding](https://user-images.githubusercontent.com/13572985/222791660-41965b84-2a84-428e-85b1-a2893f7f8f03.png)

Thanks in advance for considering!

**Comment by DSPaul** [comment]
I think the best solution here is to just add a new color option "same as parent" so that it also dynamicly updates whever you decide to change it, shouldn't be that hard. 
And don't be afraid to suggest as much as you want! It makes the app beter for everyone.

**Comment by Mifgan** [comment]
Oh, you're suggestion is even better. Thanks!

**Comment by DSPaul** [comment]
I ended up doing both. So there is a new "same as parent" colour, and you can right click a tag to create a new subtag that will have the "same as parent' colour chosen by default. Group tags will also have colours now for the purpose of passing it on to its childeren.

**Comment by Mifgan** [comment]
Thanks a lot!
