### ISSUE TITLE
Tag tree auto expands

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#32]
**Describe the bug**
Since 1.1 the entire tag tree auto expands when adding or deleting a tag, even if you just collapsed all subtags. 

**Expected behavior**
The tag tree would remember the position it had before adding the tag. 

**Alternate solution** 
A button to collapse / expand all tags. 

Thanks!

**Comment by Mifgan** [comment]
It has the same behaviour when deleting a tag.

**Comment by DSPaul** [comment]
Fixed in hotfix 1.1.1
