### ISSUE TITLE
Tags to remove doesn't need an 'Add Tag' button

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#33]
**Describe the bug**
When bulk editing an entries, both the 'Tags to Add' and 'Tags to Remove' options have a ' Add Tag' button. 

**Expected behavior**
The button should only be present for 'Tags to Add'. 

**Screenshots/files**
![afbeelding](https://user-images.githubusercontent.com/13572985/222925943-f755df98-c097-4db9-a1da-2e2cb300dea8.png)

**System info (please complete the following information):**
 - Release Version V1.1

**Comment by DSPaul** [comment]
That button should be there, it's just poorly labeled. It is used to add tags to the list of tags that need to be removed, hence why it is called "add tag". I'll rename them to `Choose Tags` or `Select Tags` or something along those lines to make it more clear.

**Comment by Mifgan** [comment]
Oh right. I totally misunderstood it then. 
I must admit I didn't click on it either.
