### ISSUE TITLE
Change paths of a file based on the given tags

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#36]
Hi! 

ComicRack had a plugin, https://github.com/Stonepaw/comicrack-library-organizer, where you could give certain tags/templates to a file and it would both rename and move that file. ie you could rename the cbz file to `Superman Vol. 1938 #703 (November, 2010).cbz` and move it to `\DC Comics\Superman (1938)`. 

It could also make new folders if the folder (ie `Superman (1938)` in above example) would exist yet. 

Could something similar be made either based on file renames and/or tags?

**Comment by DSPaul** [comment]
COMPASS was designed around linking to your files/websites and organizing those links using all of its tagging and metadata features. It does not touch your files at all and that is part of its core design. It is a radical departure from a traditional file explorer and adding features that organise your files in folders again goes against that philosophy. On top of that this seems like a really niche power user thing that would be really hard to communicate to the average user so I must disappoint you that I don't plan on adding this at the moment.

**Comment by Mifgan** [comment]
No issue. I'll pass on your message to the person who asked it.
