### ISSUE TITLE
Sorting of tags on books

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#37]
Currently when you add a bunch of tags to a book (I did mine by bulk edit) it adds them seemingly randomly. 
In this case, for the first group: I added them in this order: 
- 7th Sea
- 1e
- Fantasy
- Swashbuckling / Pirates
- Primarily D10
- Roll and Keep
- Point Based

The order on which they appeared on the books is: 
- 7th Sea
- Fantasy
- Point Based
- Roll and Keep
- 1e
- Swashbuckling / Pirates
- Primarily D10

For the second batch it changed it to the same order, but I saw I forgot to add the `7th Sea` tag. When I added in a second edit, it stayed at the end. 

![afbeelding](https://user-images.githubusercontent.com/13572985/222983936-b1ce3a3b-b445-4f37-b85a-f5d787dbef1e.png)

**Suggestion**: 
- All tags appear in a fixed alphabetical order. 
- `Prefered` An option in the settings to choose the order the tags appear, ie. alphabetically (general), alphabetically (by tag group and tag tree). 
In the latter case, in the above example the order would be: 7th Sea, 1e, Swashbuckling / Pirates `as Action / Adventure is before Fantasy`, Fantasy, Primarily D10 `as Dice is before Point Based`, Point Based, Roll and Keep.

**Comment by Mifgan** [comment]
Peculiar, on restarting the application the order of the second group (the 7th Sea 2e books), the order of the tags changed to mirror the others. 

![afbeelding](https://user-images.githubusercontent.com/13572985/222986139-85a52644-9b02-4f9f-8928-4a42b237ee59.png)

**Comment by DSPaul** [comment]
I chose to order them by what I found the most intuitive option: the same order as they appear in your tree of tags, top to bottom if you were to remove the indentations (also known as pre order depth first search) . This way they are all nicely grouped and they follow your preferred order within a group.

**Comment by Mifgan** [comment]
Thanks! That's perfect!
