### ISSUE TITLE
Saving metadata in the files

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#38]
Is there a possibility to let COMPASS save the metadata you make in the application (tags, adding of publisher, author, ISBN etc) in the file's metadata?

**Comment by DSPaul** [comment]
Technically you could but the metadata fields of a file depends on the file type so COMPASS would need to create custom metadata fields on the file which other programs aren't aware of and therefore cannot read/interpret so I don't really see the value this provides. I found [this project](https://github.com/mono/taglib-sharp) which already does this for video, audio and images so it's not impossible but I don't plan on doing this anytime soon.

**Comment by Mifgan** [comment]
Fair enough. The idea behind it was sorting files in COMPASS and then accessing it via a web client of an other software to be able to use it from several devices (that aren't Windows limited).

**Comment by DSPaul** [comment]
Well the problem there is that the custom metadata fields, if I was planning to go that route, is file system dependent and MacOS and Linux use a different filesystem from windows so you would run into problems there as well.

**Comment by Mifgan** [comment]
Hmm, very true.

**Comment by Mifgan** [comment]
Feature request can be closed for me. :)
