### ISSUE TITLE
Import Folder Clears Tags

### ISSUE THREAD

**Issue by DraftDodger42** [DSPaul/COMPASS#44]
**Describe the bug**
Using Import Folder or Import File seems to be clearing all the tags previously applied to other imported files.

**Expected behavior**
Should not clear any tags

**To Reproduce**
1. Import a file (ex test.pdf)
2. Add a tag to it
3. Import another file (or folder)
4. test.pdf no longer has tags

**System info (please complete the following information):**
 - OS: Win10
 - Release Version 1.1.2

**Comment by DSPaul** [comment]
I released a hotfix to address this, thanks for letting me know. This is a pretty nasty bug and I hope not too many people had all their tags deleted after spending hours organizing everything.
