### ISSUE TITLE
Import tags from other collections

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#51]
It's maybe linked to #24. 

If I'd make separate collections for the major gaming systems I collect, I currently either need to make all tags that I want to reuse manually again, or dig into an existing's collection `tags.xml` to copy parts to the new collection's `tags.xml` (which can lead to syntax mistakes). 
It would be neat to have some function within COMPASS where you can import a selection of tags from one collection to another collection. 
Ie
**Dungeons & Dragons** has the tags
- Core
- Supplement
  * Spell
  * Item
  * Class
  * Race
  * Bestiary
- Module
- Campaign

I want to import in **Call of Cthulhu** 
- Core
- Supplement
  * Spell
  * Bestiary
- Module
- Campaign

But not: 
- Supplement
  * Item
  * Class
  * Race

An example solution could be a button `Import Tags` where when clicked on and selected a source (which collection you want to import from) you'd get a new window within COMPASS with a dropdown with checkboxes to choose which tags to copy over to the current collection. 
Or, a new window with two columns `CollectionName1` (source collection) and `CollectionName2` (destination collection) where you can copy (and reorder?) tags from the source collection to the destination collection. That can be done for example with arrows (move to left to add, move to right to remove wrongly added tags within this editing session and maybe up and down to sort) or by dragging and dropping tags. 
In either case, it would be important that if only a child tag would be selected, that the parent tag (for the structure) would be auto selected too. Maybe a user then could manually deselect the parent if they really need to (but that seems less relevant to me). 
It would also be useful if the other data of the tag (colour) would also be copied over. 

Thanks!

**Comment by DSPaul** [comment]
To do #24 is was already planning on making a nice UI where you can pick and choose which tags to import from a tag tree so once that is done, this functionality could easily be added. Importing tags would then give you the choice between 3 options:
  
- import from a tags.xml file
- import from another collection 
- (eventually) import from a central repository of premade tag bundles. 

After choosing a set of tags from one of these options, it would show you a preview of all the tags from that source with a checkbox next to each one of them, similar to how you choose which tags a book has so you can pick and choose which ones to import.

**Comment by DSPaul** [comment]
Added in v1.6.0
