### ISSUE TITLE
Regenerate Cover / Thumbnail

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#54]
Hi! 

There are situations where a cover / thumbnail of a file could get corrupted or wrongly generated. 
If I understand it correctly, once COMPASS generates the cover and thumbnail for a file, it will keep referencing to said cover and thumbnail. If a cover and/or thumbnail would be corrupted, you currently have (for monitored folders) remove the file from the folder, remove the "broken links/missing files" from COMPASS in the settings (or manually), close COMPASS, readd the files in the folder and start COMPASS again to get them picked up, and generate a cover and thumbnail. 

Suggestion: 
Being able to right click on a selection (one file or several files) and in the dropdown menu have a `Regenerate Cover` button (which would do both cover and thumbnail). 
Or if you fear that the dropdown menu would be too crowded, a shortcut do regenerate covers for selected files, with a list of shortcuts somewhere in the settings or documentation. 

Thanks!

**Comment by DSPaul** [comment]
There is already a button that does exactly what you describe. It can be found in the edit window underneath the cover labelled "fetch" as shown in the screenshot here. I'll try to make it a bit more clear by perhaps changing the name of the button and adding a tooltip. There is however currently no way to do this for multiple files at once so I'll look into adding a button somewhere there makes that possible, could be in the context menu, could also be in bulk edit to keep it consistent or maybe in the settings somewhere, I'll experiment with it a bit. 
![afbeelding](https://user-images.githubusercontent.com/35136955/236825144-7cffef50-71b9-4a07-bc0d-2b8ced5bae1e.png)
