### ISSUE TITLE
Add columns

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#55]
It would be nice to be able to sort files in a collection based on the `Date Added` field. 
Once you have added a few hundreds (or thousands) of files to a collection, it can become hard to find which were the files added latest or which files were added at the same time. 

The later can be useful if, for instance, four files belonging to the same adventure would be added and you'd want to find these four files to add tags to them. 

ISBN could also be useful to have as a column. 

![image](https://user-images.githubusercontent.com/13572985/236897794-ee8bc737-57dc-45bc-8b4f-6c2f2dd124a6.png)

![image](https://user-images.githubusercontent.com/13572985/236898235-b56fcb6e-8c1a-487b-9249-47c4fd0306b5.png)

**Comment by DSPaul** [comment]
You can already sort by Date added in the Sorting tab, but I indeed forgot to add it to the list layout as a column 

![Image](https://user-images.githubusercontent.com/35136955/236901098-25344576-09de-48ee-a947-03d05fabab1b.png)

**Comment by DSPaul** [comment]
I have added both columns. 

> easier guessing which files belong together

There is indeed still room for improvements there and some grouping features are planned but that is another issue for another day.
