### ISSUE TITLE
Exclude specific Subfolders from Autoimport

### ISSUE THREAD

**Issue by ChromeMystic** [DSPaul/COMPASS#58]
For most active Game I have a subfolder called "Helpers" that contain things like GM Screens, Tables but also Tokens and Pictures I want to use. These often have several hundred files in there. 

I would love a way to exclude an entire Subfolder (such as tokens) from Import into Compass. So I don't get 400 files when Importing a small Indie game,

**Comment by DSPaul** [comment]
That does seem like a problem multiple people will run into and could benefit from. I'll definitely look into it.
