### ISSUE TITLE
Critical Error Upon Launching After Initial Installation

### ISSUE THREAD

**Issue by brittonica** [DSPaul/COMPASS#66]
**Issue:**
Upon initial installation of the app, I received a critical error message after attempting to open the program. Restart of Windows did not solve the issue. Message text follows:

> It seems COMPASS has run into a critical error ("The invocation of the constructor on type 'COMPASS.Windows.MainWindow' that matches the specified binding constraints threw an exception.' Line number '13' and line position '5'.).

**Screenshots/files**
![Screenshot 2024-03-16 141133](https://github.com/DSPaul/COMPASS/assets/26048615/10b46a53-ddd5-4cc7-a11e-6f97cee43e97)

Log: [all.log](https://github.com/DSPaul/COMPASS/files/14624825/all.log)

**System info:**
 - OS: Windows 11 Home
 - Release Version Version 10.0.22621 Build 22621

**Comment by DSPaul** [comment]
That is a little concerning. I'm at an event now so I can't look at it right away, I'll try check it out when I get home.

**Comment by VicenteCartas** [comment]
I got the same error, reading the log, in my case the problem was:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\vicen\AppData\Roaming\COMPASS\Collections'.

So I just created the Collections folder by hand, and it launched successfully.

**Comment by brittonica** [comment]
> So I just created the Collections folder by hand, and it launched successfully.

That did the trick. Thank you!

**Comment by DSPaul** [comment]
Ok, that tells me what's wrong, should be an easy fix when I get home, and that also explains why it only happens on fresh installs. Thank you guys for letting me know.

**Comment by brittonica** [comment]
Glad it was an easy solve. Wonderful product!

**Comment by DSPaul** [comment]
It's fixed now, sorry for the inconvenience. I'll investigate tomorrow why my tests didn't catch this. Thanks for the kind words 😄
