### ISSUE TITLE
Spelling errors on website compassapp.info

### ISSUE THREAD

**Issue by Gazook89** [DSPaul/COMPASS#70]
I can't test the actual app due to having only a Mac desktop, but I did notice some simple typos on the website.  Sorry if this is nitpicky/tedious. Mostly just spelling errors, I haven't spent enough time to make recommendations on grammar/editing.

### New way to organize

- [x] COMPASS offers divers[e] ways ...
- [x] Welcome to you[r] new Home
- [x] ... its own list of known authors and publishers, [etc].
- [x] ...new files which will then automatically be imported. ` --> ` ...then be automatically imported

### Advanced Tagging
- [x] ..., content type, genre, setting, [etc]. without the need...

### Automatic Metadata
- [x] ISBN numbers are automatically ~~detected~~ detected inside [PDFs].

### Unify your Library
- [x] additional field such a[s] the title or rating.

**Comment by DSPaul** [comment]
> Sorry if this is nitpicky/tedious.

Not at all, this is great! I'll go through them all, and proofread the whole thing again myself because clearly I didn't do that when I wrote all of this.

**Comment by DSPaul** [comment]
The changes are online, thanks again!
